import type { NextPage, GetStaticPaths, GetStaticProps} from 'next'
import Head from 'next/head'
import { PrismaClient } from '@prisma/client'
import { useState } from 'react'
import Create from '../components/Create'

const prisma = new PrismaClient()

export const getStaticProps: GetStaticProps = async ({ params } : {params: ParsedUrlQuery}) => {
  const initialIdiots = await prisma.idiot.findMany()
  return { 
    props: { initialIdiots }
  }
}

const Home: NextPage = ({ initialIdiots }) => {
  const [idiots, setIdiots] = useState(initialIdiots)

  const moreIdiots = (newIdiot) => {
    setIdiots([...idiots, newIdiot])
  }

  return (
    <div>
      <Head>
        <title>CRUD APP</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {idiots.map( (idiot, index) => (
        <figure key={index}>
          <blockquote>
            {idiot.quote}
          </blockquote>
          <figcaption>
            - By: <cite>{idiot.name}</cite>
          </figcaption>
          <hr />
        </figure>
      ))}

      <Create moreIdiots={moreIdiots} />
    </div>
  )
}

export default Home
