import type { NextPage } from 'next'

import Head from 'next/head'
import { useRouter } from 'next/router'
import { useEffect, useState, FormEvent, FormEventHandler } from 'react'

const Signup: NextPage = (): JSX.Element => {
    const router = useRouter()

    const [state, setState] = useState({ 'email': '', 'password': '' })

    const handleSubmit: FormEventHandler = async (event: FormEvent) => {
        event.preventDefault()
        try {
            const response = await fetch(`/api/auth/newuser`, {
                method: "POST",
                headers: { "Content-Type": "application/json" },
                body: JSON.stringify(state)
            })

            const user = await response.json()
            console.log(user)
        } catch (error) {
            console.error(error)
        }
    }

    const handleChange = ({ target }: { target: HTMLInputElement }) => {
        const { name, value } = target
        setState({ ...state, [name]: value });
    }

    useEffect(() => {
        let token = sessionStorage.getItem('Token')

        if (token) {
            router.push('/')
        }
    }, [])

    return (
        <>
            <Head>
                <title>Sign in</title>
                <meta name="description" content="Generated by create next app" />
            </Head>

            <style jsx>{`
                form {
                    display: flex;
                    margin: auto;
                }
            `}</style>

            <h1>Sign Up here</h1>

            <form onSubmit={handleSubmit}>
                <input
                    autoFocus
                    required
                    name="email"
                    onChange={handleChange}
                    placeholder="E-mail"
                    type="text"
                    value={state.email}
                />
                <input
                    required
                    type="password"
                    name="password"
                    onChange={handleChange}
                    placeholder="Password"
                    value={state.password}
                />
                <button>Sign me up</button>
            </form>
        </>
    )

}

export default Signup