import type { NextPage } from 'next'
import type { FormEvent, FormEventHandler } from 'react'

import Head from 'next/head'
import { useRouter } from 'next/router'
import { signIn, useSession } from 'next-auth/react'
import { useState, useEffect } from 'react'

const Signin: NextPage = (): JSX.Element => {
    const { data, status } = useSession()
    const router = useRouter()
    const [state, setState] = useState({'email': '', 'password': ''})

    const handleSubmit: FormEventHandler = async (event: FormEvent) => {
        event.preventDefault()
        const {email, password} = state

        try {
            await signIn('credentials', {email, password, redirect: false})

        } catch (error) {
            console.error(error)
        }
    }
    
    const handleChange = ({ target } : {target: HTMLInputElement}) => {
        const {name, value} = target
        setState({ ...state, [name]: value });
    }

    useEffect( () => {
        if (status === 'authenticated') {
            router.push('/')
        }
    }, [handleSubmit])

    return (
        <>
            <Head>
                <title>Sign in</title>
                <meta name="description" content="Generated by create next app" />
            </Head>

            <style jsx>{`
                form {
                    display: flex;
                    margin: auto;
                }
            `}</style>

            <h1>Sign in</h1>

            <form onSubmit={handleSubmit}>
                <input
                    autoFocus
                    required
                    name="email"
                    onChange={handleChange}
                    placeholder="E-mail"
                    type="text"
                    value={state.email}
                />
                <input
                    required
                    type="password"
                    name="password"
                    onChange={handleChange}
                    placeholder="Password"
                    value={state.password}
                />
                <button>Log in</button>
            </form>
        </>
    )
}

export default Signin